#! /bin/sh

bspc config border_width        5
bspc config window_gap          30
bspc config top_padding         5
bspc config left_padding        8
bspc config right_padding       8
bspc config bottom_padding      8

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
#bspc config focus_by_distance    	false
#bspc config history_aware_focus  	true
bspc config focus_follows_pointer 	true
bspc config pointer_follows_focus 	false
bspc config click_to_focus 			none
bspc config adaptive raise 			true

bspc config center_pseudo_tiled  true

#bspc config normal_border_color "#131313"
#bspc config focused_border_color "#d60808"
#bspc config presel_feedback_color "#d60808"

wal -R &
xrdb ${HOME}/dotfiles/xorg/.Xresources
#picom --config ${HOME}/dotfiles/others/picom.conf

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color   "$color15" # normal: not focused
bspc config active_border_color   "$color1"  # active: last focused on unfocused monitor
bspc config focused_border_color  "$color2"  # focused: currently focused
bspc config presel_feedback_color "$color1"

#bspc monitor -d      
#bspc monitor -d 1 2 3 4 5 6 7 8 9 0
bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc rule -a '*:yad' state=floating
bspc rule -a 'feh' state=floating
bspc rule -a 'Steam' state=tiled
bspc rule -a 'Zathura' state=tiled

#sh $HOME/dotfiles/bspwm/java_nonreparenting_wm_hack.sh
#dunst &
